### ISSUE TITLE
Overriding a notification's raw icon

### ISSUE THREAD

**Issue by hokomo** [dunst-project/dunst#1009]
### Issue description

I can't seem to be able to override the icon of a Discord notification using the `new_icon` setting as descibed in the manual. The body gets overriden according to the `format` setting, but not the icon. The same rule works when I test it on a notification sent with `notify-send` however. Here's the output of `dunst -print` (with some details elided with the `<home>`, `<user>` and `<channel>` variables):

```
{
    appname: 'notify-send'
    summary: '<user>'
    body: 'testing'
    icon: '/home/<home>/.config/dunst/hello.png'
    raw_icon set: false
    icon_id: '(null)'
    desktop_entry: ''
    category:
    timeout: 10000
    urgency: NORMAL
    transient: 0
    formatted: 'hello!'
    fg: #ffffff
    bg: #285577
    highlight: #1745d1
    frame: #aaaaaa
    fullscreen: show
    format: hello!
    progress: -1
    stack_tag:
    id: 2
    actions: {}
    script_count: 0
}
{
    appname: 'discord'
    summary: '<user> (<channel>)'
    body: 'testing'
    icon: '/home/<home>/.config/dunst/hello.png'
    raw_icon set: true
    icon_id: '<id>'
    desktop_entry: 'discord'
    category:
    timeout: 10000
    urgency: NORMAL
    transient: 0
    formatted: 'hello!'
    fg: #ffffff
    bg: #285577
    highlight: #1745d1
    frame: #aaaaaa
    fullscreen: show
    format: hello!
    progress: -1
    stack_tag:
    id: 1974
    actions: {
        "default": "View"
    }
    script_count: 0
}
```

The only notable difference between the two seems to be the `raw_icon` flag that's set on the Discord notification. The same issue existed before (#339), but it should've been fixed according to 86cbc1d34b. Searching the current source code I can't find similar functionality anymore.

What am I missing? Has the fix been undone? Is the `raw_icon` flag the culprit here or something else? How can I still override the icon even if the flag is set?

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.7.3`
- Install type: `package`
- Window manager / Desktop environment: `Fedora 35, i3`

<details>
<summary>Minimal dunstrc</summary>

```ini
[discord]
summary = "*<user>*"
format = "test test!"
new_icon = "~/.config/dunst/hello.png"
```
</details>
