### ISSUE TITLE
Can't override timeout if program specified it; can't override urgency

### ISSUE THREAD

**Issue by tastytea** [dunst-project/dunst#1020]
### Issue description

I'm trying to override the timeout for some notifications. It does not work when the application specified a timeout. I also discovered that I can not override the urgency.

* `notify-send -a "program" "summary" "body"` — timeout override works, urgency override does not work.
* `notify-send -a "program" -t 10000 "summary" "body"` — timeout override does not work, urgency override does not work.

#### Example notification

This is the output I get with `notify-send -a "program" -t 10000 "summary" "body"` The urgency seems to be set correctly, but it is displayed as a normal notidication.

```
{
        appname: 'program'
        summary: 'summary'
        body: 'body'
        icon: 'dialog-warning'
        raw_icon set: false
        icon_id: '(null)'
        desktop_entry: ''
        category:
        timeout: 10000
        urgency: CRITICAL
        transient: 0
        formatted: '<b>summary</b>
body'
        fg: #ffffff
        bg: #00ff00
        highlight: #1745d1
        frame: #888888
        fullscreen: show
        format: <b>%s</b>
%b
        progress: -1
        stack_tag:
        id: 2
        actions: {}
        script_count: 0
}
```

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.7.3 (2021-12-08)`
- Install type: `Gentoo repo`
- Window manager / Desktop environment: `i3`

<details>
<summary>Minimal dunstrc</summary>

```ini
[urgency_normal]
    background  = "#00ff00"
    timeout = 10

[urgency_critical]
    background  = "#ff0000"
    timeout = 0

[override_test]
    appname = "program"
    timeout = 2
    urgency = critical
```
</details>
