### ISSUE TITLE
Possible memory leak (but only on certain messages)

### ISSUE THREAD

**Issue by dpaetzel** [dunst-project/dunst#173]
Dunst version: 1.0.0-2
OS: Archlinux

On certain messages (esp. the ones that Spotify sends after the latest update) dunst's memory consumption suddenly increases by ~80 MB (while never decreasing again). Skipping these messages through dunstrc doesn't fix anything either; they don't display but dunst takes the memory nonetheless. Other messages don't cause this problem.

An example for a "bad" message is:

```
{
    appname: 'Spotify'
    summary: 'Bli Bla Blub'
    body: 'Blub'
    icon: 'info'
    category: 
    urgency: 0
    formatted: 'Bli Bla Blub
<small>Blub</small>'
    fg: #FCE94F
    bg: #000000
    id: 2
    script: (null)
}
```

While a message like this is not "bad":

```
{
    appname: 'notify-send'
    summary: 'Not bad'
    body: 'Not bad'
    icon: 'info'
    category: 
    urgency: 1
    formatted: 'Not bad
<small>Not bad</small>'
    fg: #FFFFFF
    bg: #000000
    id: 3
    script: (null)
}
```

I can't see the difference.
