### ISSUE TITLE
dunst does not display JPEG icons without a filename extension

### ISSUE THREAD

**Issue by eadmund** [dunst-project/dunst#540]
`dunst` correctly displays icons from files whose names end in '.jpeg' or '.jpg,' but it does _not_ display them when they do not.

To reproduce:

```
$ notify-send --icon /path/to/jpeg-image Test "no image displays!"
```

### Installation info

- Version: `v1.3.2-143-g896c008`
- Install type: `manually`
- Distro and version: `Debian 9 (stretch)`

**Comment by tsipinakis** [comment]
I cannot reproduce this on debian buster. I have a feeling this is something to do with `gdk-pixbuf` which we use to load icons.

Perhaps in the version that's in stretch it only looks at the extension? I will set up a stretch VM later this week to test.

**Comment by bebehei** [comment]
I can't reproduce it either. And I've tested it on Xenial, trusty and bionic now.

- What's your gdb pixbuf version?
- What does `gdk-pixbuf-query-loaders` spit out on your system? (Watch out, this program spits out much stuff. I'm only interested in the lines for the jpeg loader!)

@eadmund And to rule out a possible misbehavior[0] of dunst: How have you tested it? Have you executed any `mv` call while the notification had been shown?
----

[0]: Dunst reloads the notification icon whenever it's drawing a notification complete freshly. So if you `mv` the file and trigger a reload, the icon disappears.

**Comment by eadmund** [comment]
Looks like `gdk-pixbuf` is at 2.36.5-2+deb9u2

I get this from `gdk-pixbuf-query-loaders`:

```
…
"/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so"
"jpeg" 5 "gdk-pixbuf" "JPEG" "LGPL"
"image/jpeg" ""
"jpeg" "jpe" "jpg" ""
"\377\330" "" 100
…
```

I ran `dunst`, then used both `notify-send` and D-Bus directly to send notifications, using different JPEG files, with & without `.jpeg`/.`jpg`. I did not move any files in between sending the notification and seeing it drawn. I _did_ confirm that a file missing the final `.jpeg` works _with_ it (so it's _probably_ not a malformed file issue).

**Comment by bebehei** [comment]
@eadmund Thanks for the answer. Sadly nothing, which enlightens me.

I've written a small helper here: https://gist.github.com/bebehei/d1248deab8199ea93d877fdf126be588

Could you please clone the gist, build it and then run `./gdkpb <whateverfile>` with files both recognized by dunst and not recognized? Thanks in advance.

PS: You may need to install `libgdk-pixbuf2.0-dev` for compilation.

**Comment by eadmund** [comment]
```
myhost ➜  d1248deab8199ea93d877fdf126be588-2638dba281a5e87346028f02a5fea73f07471ab9 ./gdkpb ~/image
Testing '/home/me/image'
Name: jpeg
Desc: JPEG
Disa: 0
Supported extensions: jpeg jpe jpg
Successfully loaded '/home/me/image'

myhost ➜  d1248deab8199ea93d877fdf126be588-2638dba281a5e87346028f02a5fea73f07471ab9 ./gdkpb ~/image.jpeg
Testing '/home/me/image.jpeg'
Name: jpeg
Desc: JPEG
Disa: 0
Supported extensions: jpeg jpe jpg
Successfully loaded '/home/me/image.jpeg'
```

It's weird, isn't it?

**Comment by bebehei** [comment]
Well, that's interesting. Some things have gone south somewhere.

So, the only thing, which still could help and give some clues: a logfile.

Could you please run `dunst -print -verbosity info`. Fire the notification and send the log?

**Comment by eadmund** [comment]
Here you go. `notify-send --icon ~/image foobar door` yields:

```
./dunst -print -verbosity info
MESSAGE: 'allow_markup' is deprecated, please use 'markup' instead.
MESSAGE: The option 'icon_folders' is deprecated, please use 'icon_path' instead.
MESSAGE: The frame section is deprecated, width has been renamed to frame_width and moved to the global section.
MESSAGE: The frame section is deprecated, color has been renamed to frame_color and moved to the global section.
{
        appname: 'notify-send'
        summary: 'foobar'
        body: 'door'
        icon: '/home/me/image'
        raw_icon set: false
        category:
        timeout: 10000
        urgency: NORMAL
        transient: 0
        formatted: '<b>foobar</b>
door'
        fg: #ffffff
        bg: #285577
        frame: #aaaaaa
        fullscreen: show
        progress: -1
        id: 2
        script: (null)
}
```

My only other guess is that the image in question is quite large (512×512). Maybe dunst (or the library it's using) doesn't know how to scale it?
