### ISSUE TITLE
timeout beyond ~10 minutes does not work

### ISSUE THREAD

**Issue by mithodin** [dunst-project/dunst#657]
I'm trying to have a notification time out at n minutes by calling `notify-send -t $(( 60000*$n )) "some message"`. This works correctly for n <= 10, but fails for n >= 15 (I could pinpoint it further if neccessary) in the sense that the notification just keeps showing after the supposed timeout.

I have checked with dbus-monitor, and the transmitted information seems correct in all cases, so I suspect that this is a bug in dunst and not somewhere else.

### Installation info

- Version: `v1.4.1`
- Install type: `package` or `manual`
- Distro and version: `linux mint 19.2`, kernel `5.0.0`

**Comment by bebehei** [comment]
We had a similar bug 2 weeks ago. Does the current master work? (PR #647 fixed it).

What does `dunst -print` say when running dunst on the command line. and sending a notification in parallel?

**Comment by mithodin** [comment]
```
{
    appname: 'notify-send'
    summary: '15 minute timeout'
    body: ''
    icon: 'dialog-information'
    raw_icon set: false
    icon_id: 'dialog-information'
    desktop_entry: ''
    category:
    timeout: 900000
    urgency: NORMAL
    transient: 0
    formatted: '<b>15 minute timeout</b>'
    fg: #ffffff
    bg: #285577
    frame: #aaaaaa
    fullscreen: show
    progress: -1
    stack_tag:
    id: 2
    actions: {}
    script: (null)
}
```
with both 1.4.1 and master. But I'll test with master to see whether it is already fixed.
