### ISSUE TITLE
icons stopped displaying

### ISSUE THREAD

**Issue by prankousky** [dunst-project/dunst#703]
Hi everybody,

I am using `Dunst - A customizable and lightweight notification-daemon 1.4.1 (2019-07-03)` on Arch Linux, installed via `AUR`. WM `i3-gaps`, composite manager `picom` (currently disabled).

Output of `dunst -c dunstrc -print`

```
{
        appname: 'dunstify'
        summary: 'dunst neu gestartet.'
        body: ''
        icon: '/home/me/.config/helpers/icons/dunst96.png'
        raw_icon set: false
        icon_id: '/home/me/.config/helpers/icons/dunst96.png'
        desktop_entry: ''
        category:
        timeout: 10000
        urgency: LOW
        transient: 0
        formatted: 'dunst neu gestartet.'
        fg: #E30689
        bg: #000000
        frame: #E30689
        fullscreen: show
        progress: -1
        stack_tag:
        id: 2
        actions: {}
        script: (null)
}
```

I use `pywal` and a template file to generate my `dunstrc`, but this problem occurred before using `pywal` at all, so I doubt that it is connected to the issue.

My `dunstrc` looks like this

```
# New Start: A modern Arch workflow built with an emphasis on functionality.
# Copyright (C) 2018 Donovan Glover

# NOTE: This file is automatically generated by pywal. Do not edit it by hand.

[global]
# Welcher Bildschirm?
	monitor = DisplayPort-2
    # Make the width 3740 (3840 - 100), have 50 left margin and 95 above
    geometry = x0-0+30

    # Show multiple notifications in the same box
    separator_height = 10

    # Add vertical padding to the inside of the notification
    padding = 25

    # Add horizontal padding for when the text gets long enough
    horizontal_padding = 25

    # The frame color and width of the notification
    frame_color = "#E30689"
    frame_width = 10

    # How long a user needs to be idle for sticky notifications
    idle_threshold = 120

    # Font and typography settings
    # font = Fira Mono 11
    font = Hack 15
    alignment = center
    word_wrap = yes

    # Format for how notifications will be displayed
    # Usage: `notify-send 'Title' 'Summary'`
    # format = "<b>%s</b>: %b"

    # Allow some HTML tags like <i> and <u> in notifications
    markup = full

# These are the keybindings used to control dunst notifications
[shortcuts]
    close = ctrl+space
    close_all = ctrl+shift+space
    # history = ctrl+grave this caused issues, so I commented it out

# Set the background and foreground (text) color for all notifications
[urgency_low]
    background = "#000000"
    foreground = "#E30689"

[urgency_normal]
    background = "#000000"
    foreground = "#01ABE9"

[urgency_critical]
    background = "#000000"
    foreground = "#F4E70A"

# aus alter Config übernommen
	sort = yes
	separator_color = frame
	line_height = 25
	# format = "%i<span foreground='#f3f4f5'><b>%s %p</b></span>\n%b"
	# format = "%i %s %p\n%b"
	alignment = center
	corner_radius = 0
	stack_duplicates = true
	hide_duplicate_count = false
	show_indicators = yes
	icon_position = right
	icon_path = /home/me/.config/helpers/icons
	max_icon_size = 96
	stick_history = yes
	history_length = 20
	title = Dunst
	class = Dunst
	startup_notification = true
	per_monitor_dpi = true
	shrink = no
	transparency = 20
	notification_height = 25
	ellipsize = middle
	ignore_newline = no

# vim:ft=cfg
```

When I run something in the likes of `notify-send -i $HOME/.config/helpers/icons/someicon96.png` // `notify-send -i someicon96.png` // `dunstify -u low -i /home/me/.config/helpers/icons/someicon96.png`, etc. etc., it will display the notification fine (including modified colors from me `dunstrc` if I changed the pywal template beforehand), but it will never display any icon. The icons used to work, so the file format should be correct, as should the size. When I run `feh $HOME/.config/helpers/icons/i3.png`, it will display the icon.

What am I doing wrong? Thank you for your support :)
