### ISSUE TITLE
Ability to override `hide_duplicate_count`

### ISSUE THREAD

**Issue by smhmd** [dunst-project/dunst#712]
In custom sections (or profiles?), I'm matching some notifications to use dunst notifcations as toasts and would like to be able to override `hide_duplicate_count` on these notifications.

specifically:
```toml
[my-toast]
	summary = "this is a toast"
	hide_duplicate_count = true
```
 
### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon v1.4.1-50-g6b60c52`
- Install type: `yay -S dunst-git`
- Distro and version: `Linux manjaro 5.6.6-1-MANJARO`
